Repository SEMOSS/semoss-ui, pull requests merged in 2025-05, with the labels that each got.

#993 [245] Allow Command + S save shortcut for Mac users
  packages/client/src/components/blocks-workspace/BlocksWorkspaceActions.tsx
  packages/client/src/components/common/File/FileEditor.tsx
Labels: enhancement, good first issue

#1048 test(renderer): add chip block test
  libs/renderer/src/testing/block-defaults/ChipBlock.spec.tsx
Labels: Test

#1032 fix(client): swapping dataTestId to Id on Notifications
  libs/ui/src/components/Notification/Notification.tsx
  packages/client/src/components/settings/UserTable.tsx
  packages/client/src/pages/HomePage.tsx
  packages/client/src/pages/PlatformMessages.tsx
  packages/client/src/pages/app/AppDetailPage.tsx
  packages/client/src/pages/app/AppPage.tsx
  packages/client/src/pages/app/NewAppPage.tsx
  packages/client/src/pages/engine/EngineCatalogPage.tsx
  packages/client/src/pages/engine/EngineMetadataPage.tsx
  packages/client/src/pages/engine/EngineQAPage.tsx
  packages/client/src/pages/import/EstablishConnectionPage.tsx
  packages/client/src/pages/jobs/DeleteJobModal.tsx
  packages/client/src/pages/jobs/HistoryRow.tsx
  packages/client/src/pages/jobs/JobBuilderModal.tsx
  packages/client/src/pages/jobs/JobsPage.tsx
  packages/client/src/pages/jobs/JobsTable.tsx
  packages/client/src/pages/prompt/PromptModal.tsx
  packages/client/src/pages/prompt/PromptPage.tsx
  packages/client/src/pages/settings/AdminQueryPage.tsx
  packages/client/src/pages/settings/ConfigurationsPage.tsx
  packages/client/src/pages/settings/MyProfilePage.tsx
  packages/client/src/pages/settings/ProjectSettingsPage.tsx
  packages/client/src/pages/settings/SettingsIndexPage.tsx
  packages/client/src/pages/settings/SettingsLayout.tsx
  packages/client/src/pages/settings/TeamsSettingsPage.tsx
  packages/legacy/core/components/catalog/catalog.directive.html
  packages/legacy/core/components/import/import-app/import-app.directive.html
  packages/legacy/core/components/import/import-copy/import-copy.directive.html
  packages/legacy/core/components/import/import-file-flat/import-file-flat.directive.html
  packages/legacy/core/components/upload-project/upload-project.directive.html
  packages/legacy/widgets/federate/federate.directive.html
Labels: Bug
